# Generated by Django 4.2 on 2023-04-13 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0004_rename_trait_name_trait_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trait",
            old_name="created_ad",
            new_name="created_at",
        ),
    ]
